name: "Require release tip tag (compat)"
description: "Compatibility shim for require-release-tip action"
inputs:
  release_branch:
    description: "Release branch name to validate against"
    required: false
    default: "mcr/release"
  remote:
    description: "Git remote name to fetch"
    required: false
    default: "origin"
  allow_merge_commits:
    description: "Allow tags that point to merge commits"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Require release tip tag
      uses: ./actions/require-release-tip
      with:
        release_branch: ${{ inputs.release_branch }}
        remote: ${{ inputs.remote }}
        allow_merge_commits: ${{ inputs.allow_merge_commits }}
